version: '3.1'

services:
  cache:
    image: redis:6
    container_name: liquidator-dev-cache
    ports:
      - 6379:6379
  database:
    image: postgres
    container_name: liquidator-dev-database
    environment:
      POSTGRES_DB: liquidator
      POSTGRES_USER: liquidator
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./data/dev/postgres:/var/lib/postgresql/data
